# 設定を書きます
import os

SECRET_KEY = os.getenv("SECRET_KEY")
OPEN_WEATHER_API_TOKEN = os.getenv("OPEN_WEATHER_API_TOKEN")
JSON_AS_ASCII = os.getenv("JSON_AS_ASCII")
DEBUG = os.getenv("DEBUG")
MAIL_SERVER = os.getenv("MAIL_SERVER")
MAIL_PORT = os.getenv("MAIL_PORT")
MAIL_USE_TLS = os.getenv("MAIL_USE_TLS")
MAI_USE_SSL = os.getenv("MAIL_USE_SSL")
MAIL_USERNAME = os.getenv("MAIL_USERNAME")
MAIL_PASSWORD = os.getenv("MAIL_PASSWORD")
MAIL_DEFAULT_SENDER = os.getenv("MAIL_DEFAULT_SENDER")
MAIL_SUPPRESS_SEND = os.getenv("MAIL_SUPPRESS_SEND")
